export const CatalogData = [
  {
    id: 1,
    title: "THE WOODSHOP - ALPS",
    slug: "the-woodshop-alps",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=800&auto=format&fit=crop",
    viewerUrl: "https://e.issuu.com/embed.html?d=the_woodshop_alps",
  },
  {
    id: 2,
    title: "THE CARMEL COLLECTION",
    slug: "the-carmel-collection",
    image: "https://arcaww.com/CMS/media/33767/portada-carmel.png",
    viewerUrl: "https://e.issuu.com/embed.html?d=the_carmel_collection",
  },
  {
    id: 3,
    title: "ARCA BOOKS",
    slug: "arca-books",
    image: "https://images.unsplash.com/photo-1589998059171-988d887df646?q=80&w=800&auto=format&fit=crop",
    viewerUrl: "https://e.issuu.com/embed.html?d=arca_books",
  },
  {
    id: 4,
    title: "ARCA X TOGNON",
    slug: "arca-x-tognon",
    image: "https://images.unsplash.com/photo-1512486130939-2c4f79935e4f?q=80&w=800&auto=format&fit=crop",
    viewerUrl: "https://e.issuu.com/embed.html?d=arca_x_tognon",
  },
  {
    id: 5,
    title: "ARCA IVORY TRAVERTINE",
    slug: "arca-ivory-travertine",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop",
    viewerUrl: "https://e.issuu.com/embed.html?d=arca_ivory_travertine",
  },
  {
    id: 6,
    title: "ARCA LUXURY PRODUCTS & CREATIVE COLLABORATIONS",
    slug: "arca-luxury-products",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=800&auto=format&fit=crop",
    viewerUrl: "https://e.issuu.com/embed.html?d=arca_luxury_products",
  },
  {
    id: 7,
    title: "SIGNATURE SURFACES 2023",
    slug: "signature-surfaces-2023",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800&auto=format&fit=crop",
    viewerUrl: "https://e.issuu.com/embed.html?d=signature_surfaces_2023",
  },
  {
    id: 8,
    title: "ARCA X MEYER DAVIS - ETERNA",
    slug: "arca-x-meyer-davis-eterna",
    image: "https://arcaww.com/CMS/media/1553/3.png",
    viewerUrl: "https://e.issuu.com/embed.html?d=arca_x_meyer_davis",
  },
  {
    id: 9,
    title: "TUNDRA | ATLAS BEIGE (MX)",
    slug: "tundra-atlas-beige-mx",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    viewerUrl: "https://e.issuu.com/embed.html?d=tundra_atlas_beige_mx",
  },
  {
    id: 10,
    title: "THE WOODSHOP - COMPORTA",
    slug: "the-woodshop-comporta",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop",
    viewerUrl: "https://e.issuu.com/embed.html?d=the_woodshop_comporta",
  },
  {
    id: 11,
    title: "ARCA X VINCENT VAN DUYSEN - GRAVITAS",
    slug: "arca-x-vincent-van-duysen-gravitas",
    image: "https://arcaww.com/CMS/media/1542/gravitas.jpg",
    viewerUrl: "https://e.issuu.com/embed.html?d=arca_vincent_van_duysen",
  },
  {
    id: 12,
    title: "TUNDRA BEIGE | ATLAS BEIGE",
    slug: "tundra-beige-atlas-beige",
    image: "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?q=80&w=800&auto=format&fit=crop",
    viewerUrl: "https://e.issuu.com/embed.html?d=tundra_beige_atlas_beige",
  },
  {
    id: 13,
    title: "NUDO",
    slug: "nudo",
    image: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=800&auto=format&fit=crop",
    viewerUrl: "https://e.issuu.com/embed.html?d=nudo",
  },
  {
    id: 14,
    title: "TERRACOTTA HANDMADE TILES BY ARCA",
    slug: "terracotta-handmade-tiles",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop",
    viewerUrl: "https://e.issuu.com/embed.html?d=terracotta_tiles",
  },
];
