export const mediaLinks = [
  {
    id: 1,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Community Impact Newspaper",
    DATE: " July 3 - Aug 7, 2021",
    EDITION: "Volume 11, Issue 5, Page 16",
    LINK: "https://editions.communityimpact.com/view/704356651/16/",
  },
  {
    id: 2,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Paper City",
    DATE: "September 2021",
    EDITION: "Dallas, Page 13 - 14",
    LINK: "http://papercitymagazine.uberflip.com/i/1405904-papercity-dallas-september-2021/13?",
  },
  {
    id: 3,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Community Impact Newspaper",
    DATE: "Sept 6 - Oct 2, 2021",
    EDITION: "Volume 11, Issue 7, Page 22",
    LINK: "https://editions.communityimpact.com/view/838292375/22/",
  },
  {
    id: 4,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Community Impact Newspaper",
    DATE: "Oct 3 - 31, 2021",
    EDITION: "Volume 11, Issue 8, Page 10",
    LINK: "https://editions.communityimpact.com/view/533419637/10/",
  },
  {
    id: 5,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Paper City",
    DATE: "November 2021",
    EDITION: "Dallas, Page 15 - 16",
    LINK: "http://papercitymagazine.uberflip.com/i/1420844-papercity-dallas-november-2021/15?",
  },
  {
    id: 6,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Community Impact Newspaper",
    DATE: "Nov 1 - Dec 5, 2021",
    EDITION: "Volume 11, Issue 9, Page 14",
    LINK: "https://editions.communityimpact.com/view/770494646/14/",
  },
  {
    id: 7,
    IMAGE: "",
    CATEGORY: "Article",
    WEBSITE: "Paper City",
    DATE: "December 9, 2021",
    LINK: "https://www.papercitymag.com/society/dallas-design-taxila-stone-showroom-surfaces-stone-artists-designers/",
    HEADING:
      "Taxila Stone Celebrates Local Artists and Designers at Its Dallas Showroom",
    BODY_TEXT:
      "An inspiring night for design professionals, the Taxila Stone Designer Showroom event was well attended by a variety of industry leaders — from local property owners and architects to the city’s most celebrated designers, talented artists, and design-savvy individuals in the community.",
  },
  {
    id: 8,
    IMAGE: "",
    CATEGORY: "Article",
    WEBSITE: "Modern Luxury",
    DATE: "December 2021",
    EDITION: "Dallas, Page 184",
    LINK: "http://digital.modernluxury.com/publication/?m=3620&amp;i=729885&amp;p=186&amp;ver=html5",
    HEADING: "Interview with the CEO, Hari Polavarapu",
    BODY_TEXT:
      "As the CEO of Taxila Stone, a wholesale distributor of hand-selected natural and engineered stone surfaces, Hari Polavarapu is surrounded with timeless beauty.",
  },
  {
    id: 9,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Paper City",
    DATE: "January &amp; February 2022",
    EDITION: "Dallas, Page 15 - 16",
    LINK: "http://papercitymagazine.uberflip.com/i/1439511-papercity-dallas-january-february-2022/15?",
  },
  {
    id: 10,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Modern Luxury - Interiors",
    DATE: "Febraury 2022",
    EDITION: "Texas, Page 22 - 23",
    LINK: "https://digital.modernluxury.com/publication/?m=22590&amp;i=737416&amp;p=24&amp;ver=html5",
  },
  {
    id: 11,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Modern Luxury",
    DATE: "March 2022",
    EDITION: "Dallas, Page 55",
    LINK: "https://digital.modernluxury.com/publication/?m=3620&amp;i=738656&amp;p=56&amp;ver=html5",
  },
  {
    id: 12,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Paper City",
    DATE: "March 2022",
    EDITION: "Dallas, Page 58",
    LINK: "http://papercitymagazine.uberflip.com/i/1455228-papercity-dallas-march-2022/57?",
  },
  {
    id: 13,
    IMAGE: "",
    CATEGORY: "Article",
    WEBSITE: "Voyage Dallas",
    DATE: "March 17, 2022",
    LINK: "http://voyagedallas.com/interview/conversations-with-josh-caballero/",
    HEADING: "Conversations with Josh Caballero",
    BODY_TEXT:
      "Hi Josh, so excited to have you with us today. What can you tell us about your story?\nHow we got here is a complex story. Here’s the short version – The principals of the three show rooms opening in the metroplex come from hospitality and furniture backgrounds.",
  },
  {
    id: 14,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Paper City",
    DATE: "April 2022",
    EDITION: "Dallas, Page 7-8",
    LINK: "http://papercitymagazine.uberflip.com/i/1462583-papercity-dallas-april-2022/7?",
  },
  {
    id: 15,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Paper City",
    DATE: "May 2022",
    EDITION: "Dallas, Page 52",
    LINK: "http://papercitymagazine.uberflip.com/i/1465756-papercity-dallas-may-2022/51?",
  },
  {
    id: 16,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Modern Luxury - Interiors",
    DATE: "May 2022",
    EDITION: "Texas, Page 16-17",
    LINK: "https://digital.modernluxury.com/publication/?m=22590&amp;i=746790&amp;p=18&amp;ver=html5",
  },
  {
    id: 17,
    IMAGE: "",
    CATEGORY: "Article",
    WEBSITE: "M2G Ventures",
    DATE: "May 26, 2022",
    LINK: "https://www.m2gventures.com/press/m2gs-urban-industrial-redevelopment-lands-two-tenants/",
    HEADING: "M2G’s Urban Industrial Redevelopment Lands Two Tenants",
    BODY_TEXT:
      "M2G Ventures, a North Texas-based real estate investment and development company, announced two tenants under construction, Dynasty Spirits and Taxila Stone totaling 136,020 square feet, at M2G’s urban industrial redevelopment, PROTO Park.",
  },
  {
    id: 18,
    IMAGE: "",
    CATEGORY: "Article",
    WEBSITE: "Fort Worth Inc.",
    DATE: "May 26, 2022",
    LINK: "https://fortworthinc.com/news/two-companies-moving-into-m2g-ventures-proto-park/",
    HEADING: "Two Companies Moving into M2G Ventures' PROTO Park",
    BODY_TEXT:
      "Taxila Stone is a wholesale distributor of hand-selected natural and engineered stone surfaces and works with some of the most exclusive stone quarries in the world, from marble to granite, quartzite, onyx, quartz, and travertine, among others.",
  },
  {
    id: 19,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Paper City",
    DATE: "June 2022",
    EDITION: "Dallas, Page 48",
    LINK: "http://papercitymagazine.uberflip.com/i/1468547-papercity-dallas-june-2022/47?",
  },
  {
    id: 20,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Modern Luxury",
    DATE: "July 2022",
    EDITION: "Dallas, Page 23",
    LINK: "https://digital.modernluxury.com/publication/?m=3620&amp;i=751131&amp;p=24&amp;ver=html5",
  },
  {
    id: 21,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Modern Luxury - Guide to the Design District",
    DATE: "2022-23",
    EDITION: "Dallas, Page 6-7",
    LINK: "https://digital.modernluxury.com/publication/?m=60522&amp;i=750374&amp;p=8&amp;ver=html5",
  },
  {
    id: 22,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Paper City",
    DATE: "July-August 2022",
    EDITION: "Dallas, Page 9-10",
    LINK: "http://papercitymagazine.uberflip.com/i/1471747-papercity-dallas-july-august-2022/9?",
  },
  {
    id: 23,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Modern Luxury - Interiors",
    DATE: "August 2022",
    EDITION: "Texas, Page 18-19",
    LINK: "https://digital.modernluxury.com/publication/?m=22590&amp;i=753788&amp;p=20&amp;pp=2&amp;ver=html5\\",
  },
  {
    id: 24,
    IMAGE: "",
    CATEGORY: "Article",
    WEBSITE: "M2G Ventures",
    DATE: "August 2022",
    LINK: "https://www.m2gventures.com/blog/tenant-spotlight-taxila-stone/",
    HEADING: "Taxila Stone | PROTO Park - M2G Ventures",
    BODY_TEXT:
      "Beyond the Surface\nTaxila Stone is unlike any other wholesale stone distributor. As a wholesale distributor of hand-selected natural and engineered stone surfaces, Taxila works with some of the most exclusive stone quarries in the world, from marble to granite, quartzite, onyx, quartz, and travertine, to name a few.",
  },
  {
    id: 25,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Modern Luxury",
    DATE: "September 2022",
    EDITION: "Dallas, Page 59",
    LINK: "https://digital.modernluxury.com/publication/?m=3620&amp;i=757880&amp;p=60&amp;ver=html5",
  },
  {
    id: 26,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Paper City",
    DATE: "September 2022",
    EDITION: "Dallas, Page 27-28",
    LINK: "http://papercitymagazine.uberflip.com/i/1477684-papercity-dallas-september-2022/27?",
  },
  {
    id: 27,
    IMAGE: "",
    CATEGORY: "Article",
    WEBSITE: "Newswires",
    DATE: "September 29, 2022",
    LINK: "https://www.einnews.com/pr_news/593238362/international-italian-luxury-brand-minotticucine-and-maistri-are-coming-to-dallas-opening-their-kitchen-design-showroom",
    HEADING:
      "International Italian Luxury Brand minotticucine and MAISTRI Are Coming to Dallas, Opening Their Kitchen Design Showroom",
    BODY_TEXT:
      "International Italian luxury brand minotticucine is coming to the Dallas Design District, opening their first kitchen design showroom in Texas on October 13th.",
  },
  {
    id: 28,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Modern Luxury - Interiors",
    DATE: "October 2022",
    EDITION: "Dallas, Page 10-11",
    LINK: "https://digital.modernluxury.com/publication/?m=22590&amp;i=764168&amp;p=12&amp;pp=2&amp;ver=html5",
  },
  {
    id: 29,
    IMAGE: "",
    CATEGORY: "Article",
    WEBSITE: "Home Furnishings Business",
    DATE: "October 5, 2022",
    LINK: "http://hfbusiness.com/hfbnow/articleid/22873/minotticucine-and-taxila-stone-to-bring-stand-alone-showroom-to-dallas",
    HEADING:
      "minotticucine and Taxila Stone to Bring Stand Alone Showroom to Dallas",
    BODY_TEXT:
      "International Italian luxury brand minotticucine is coming to the Dallas Design District, opening their first kitchen design showroom in Texas.",
  },
  {
    id: 30,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Paper City",
    DATE: "October 2022",
    EDITION: "Dallas, Page 44",
    LINK: "http://papercitymagazine.uberflip.com/i/1480367-papercity-dallas-october-2022/43?",
  },
  {
    id: 31,
    IMAGE: "",
    CATEGORY: "Article",
    WEBSITE: `Furniture, Lighting `,
    DATE: "October 10, 2022",
    LINK: "https://www.furniturelightingdecor.com/international-italian-luxury-brand-minotticucine-coming-dallas",
    HEADING:
      "International Italian Luxury Brand minotticucine coming to Dallas",
    BODY_TEXT:
      "International Italian luxury brand minotticucine is coming to the Dallas Design District, opening their first kitchen design showroom in Texas.",
  },
  {
    id: 32,
    IMAGE: "",
    CATEGORY: "Article",
    WEBSITE: "Business of Home",
    DATE: "October 31, 2022",
    LINK: "https://businessofhome.com/articles/schumacher-s-new-space-in-nashville-jeremiah-brent-opens-an-la-flagship-and-more",
    HEADING:
      "Taxila Stone collaborated with minotticucine to open a showroom in the Dallas Design District.",
    BODY_TEXT:
      "The brand’s only stand-alone location in North America, the nearly 6,000-square-foot space features personalized and minimalist kitchen designs and stone-sourcing options for surfaces.",
  },
  {
    id: 33,
    IMAGE: "",
    CATEGORY: "Featured",
    WEBSITE: "Modern Luxury",
    DATE: "November 2022",
    EDITION: "Dallas, Page 69",
    LINK: "https://digital.modernluxury.com/publication/?m=3620&amp;i=765202&amp;p=70&amp;ver=html5",
  },
  {
    id: 34,
    IMAGE: "",
    CATEGORY: "Article",
    WEBSITE: "Paper City",
    DATE: "November 3, 2022",
    EDITION: "",
    LINK: "https://www.papercitymag.com/home-design/texas-design-week-dallas-showcases-bespoke-interiors-minotticucine/",
  },
  {
    id: 35,
    IMAGE: "",
    CATEGORY: "Article",
    WEBSITE: "Paper City",
    DATE: "November 8, 2022",
    EDITION: "",
    LINK: "https://www.papercitymag.com/home-design/minotticucine-dallas-design-district-luxury-italian-kitchen-maistri/",
  },
];
