export const videoLinks = [
  {
    id: 1,
    CATEGORY: "Products",
    TITLE: "Semi Precious Line of Stones for Home and Beyond",
    COMPANY: "Taxila Stone",
    LINK: "https://youtube.com/embed/2LaOMBcbdZ8",
  },
  {
    id: 2,
    CATEGORY: "About",
    TITLE: "Taxila Stone - Welcome Tour feat. Samurai",
    COMPANY: "Taxila Stone",
    LINK: "https://youtube.com/embed/7zLOyBf06QE",
  },
  {
    id: 3,
    CATEGORY: "Products",
    TITLE: "Aurisina Fiorita Italian Marble | Taxila Stone",
    COMPANY: "Taxila Stone",
    LINK: "https://youtube.com/embed/T5mXTuhBi90",
  },
  {
    id: 4,
    CATEGORY: "Products",
    TITLE: "Calacatta Lux Beautiful White Quartzite Marble | Countertops",
    COMPANY: "Taxila Stone",
    LINK: "https://youtube.com/embed/snUhZoncyVc",
  },
  {
    id: 5,
    CATEGORY: "Products",
    TITLE: "Pink Cristalo Quartzite | Perfect for countertop | Taxila Stone",
    COMPANY: "Taxila Stone",
    LINK: "https://youtube.com/embed/1ZNKztWhu9E",
  },
  {
    id: 6,
    CATEGORY: "Products",
    TITLE: "Mont Blanc Quartzite | Taxila Stone",
    COMPANY: "Taxila Stone",
    LINK: "https://youtube.com/embed/zpWiyDsANzU",
  },
  {
    id: 7,
    CATEGORY: "About",
    TITLE: "Taxila Stone: Looking Beyond the Surface",
    COMPANY: "Taxila Stone",
    LINK: "https://youtube.com/embed/JZ4k2zgkf1E",
  },
  {
    id: 8,
    CATEGORY: "About",
    TITLE: "One stop for All Stones | Taxila Stone",
    COMPANY: "Taxila Stone",
    LINK: "https://youtube.com/embed/yXJ37DnoI7g",
  },
  {
    id: 9,
    CATEGORY: "Products",
    TITLE: "Introducing Quartzites - The New Way to Life | TAXILA STONE",
    COMPANY: "Taxila Stone",
    LINK: "https://youtube.com/embed/pa1drdIOfN8",
  },
  {
    id: 10,
    CATEGORY: "Products",
    TITLE: "Bianco Covaleno Venato - A Painting Set in Stone | TAXILA STONE",
    COMPANY: "Taxila Stone",
    LINK: "https://youtube.com/embed/OWL2ePuTlWY",
  },
  {
    id: 11,
    CATEGORY: "About",
    TITLE: "Inspired by Nature, for You, and Your Home",
    COMPANY: "Taxila Stone",
    LINK: "https://youtube.com/embed/1A3XheL6ZGA",
    Column6: "Shorts",
  },
  {
    id: 12,
    CATEGORY: "How to",
    TITLE: "THE MISHAPS EP1: Food stains",
    COMPANY: "Quartzforms Spa",
    LINK: "https://youtube.com/embed/GzbKRvbwxx8",
  },
  {
    id: 13,
    CATEGORY: "How to",
    TITLE: "THE MISHAPS EP2: Thermal shock",
    COMPANY: "Quartzforms Spa",
    LINK: "https://youtube.com/embed/-W60PUHsBA8",
  },
  {
    id: 14,
    CATEGORY: "How to",
    TITLE: "THE MISHAPS EP3: Damaged kitchen top",
    COMPANY: "Quartzforms Spa",
    LINK: "https://youtube.com/embed/BO1BdMZrARw",
  },
  {
    id: 15,
    CATEGORY: "How to",
    TITLE: "THE MISHAPS EP4: Blob of silicone",
    COMPANY: "Quartzforms Spa",
    LINK: "https://youtube.com/embed/1Wv7z_IeBwI",
  },
  {
    id: 16,
    CATEGORY: "How to",
    TITLE: "THE MISHAPS EP5: Knife blade marks",
    COMPANY: "Quartzforms Spa",
    LINK: "https://youtube.com/embed/vbfDhkpCbXk",
  },
  {
    id: 17,
    CATEGORY: "How to",
    TITLE: "THE MISHAPS EP6: Marks and stains",
    COMPANY: "Quartzforms Spa",
    LINK: "https://youtube.com/embed/fgkPbyv0iEE",
  },
  {
    id: 18,
    CATEGORY: "Process",
    TITLE: "IDYLIUM - Cutting and Processing of the Slabs",
    COMPANY: "IDYLIUM Milano",
    LINK: "https://youtube.com/embed/awtx3FTOvdU",
  },
  {
    id: 19,
    CATEGORY: "Products",
    TITLE: "IDYLIUM - Automobili Lamborghini Surfaces",
    COMPANY: "IDYLIUM Milano",
    LINK: "https://youtube.com/embed/p4qaBMaDtas",
  },
  {
    id: 20,
    CATEGORY: "Products",
    TITLE: "IDYLIUM - Papirio, Missori Collection - The Metals -",
    COMPANY: "IDYLIUM Milano",
    LINK: "https://youtube.com/embed/kxaP_BIEGO4",
  },
  {
    id: 21,
    CATEGORY: "Process + Products",
    TITLE: "minotticucine terra poured bronze",
    COMPANY: "asso group",
    LINK: "https://youtube.com/embed/Hol3sDer35c",
  },
  {
    id: 22,
    CATEGORY: "Products",
    TITLE: "minotticucine teatro",
    COMPANY: "asso group",
    LINK: "https://youtube.com/embed/2p10uQWyXzU",
  },
  {
    id: 23,
    CATEGORY: "Products",
    TITLE: "Maistri Giza 2021",
    COMPANY: "asso group",
    LINK: "https://youtube.com/embed/Ikb-fiImRgs",
  },
  {
    id: 24,
    CATEGORY: "Products",
    TITLE: "minotticucine maya oro24K",
    COMPANY: "asso group",
    LINK: "https://youtube.com/embed/BtcCSZS0Y8U",
  },
  {
    id: 25,
    CATEGORY: "Process + Products",
    TITLE: "Essenze di Luce | Corporate Movie 2020",
    COMPANY: "Essenze di Luce",
    LINK: "https://youtube.com/embed/k2R34IUZH2M",
  },
  {
    id: 26,
    CATEGORY: "Process",
    TITLE: "Stake | Production of lighting system in stainless steel",
    COMPANY: "Essenze di Luce",
    LINK: "https://youtube.com/embed/4XTqOooa51o",
  },
  {
    id: 27,
    CATEGORY: "Products",
    TITLE: "Menir Pool | Installation @ Quellenhof Lazise, Italy",
    COMPANY: "Essenze di Luce",
    LINK: "https://youtube.com/embed/dk3RMB5ku1g",
  },
  {
    id: 28,
    CATEGORY: "Products",
    TITLE: "Stake in Marble Trani @ Stonecity, Italy",
    COMPANY: "Essenze di Luce",
    LINK: "https://youtube.com/embed/Tygdb-yBD3Y",
  },
  {
    id: 29,
    CATEGORY: "Products",
    TITLE: "Stake in Black Pillar",
    COMPANY: "Essenze di Luce",
    LINK: "https://youtube.com/embed/VGQaoui85BU",
  },
  {
    id: 30,
    CATEGORY: "Process",
    TITLE: "Making Menhir Sound by Essenze di Luce",
    COMPANY: "Essenze di Luce",
    LINK: "https://youtube.com/embed/2nnMTfLFSt4",
  },
  {
    id: 31,
    CATEGORY: "Process",
    TITLE: "Menhir di Luce Labeling",
    COMPANY: "Essenze di Luce",
    LINK: "https://youtube.com/embed/-LI08hYN5Pc",
  },
  {
    id: 32,
    CATEGORY: "Process",
    TITLE: "Domiziani's handcraft",
    COMPANY: "Domiziani Design",
    LINK: "https://youtube.com/embed/AIz0rQzXMss",
  },
  {
    id: 33,
    CATEGORY: "Process",
    TITLE: "We see stone for what it can be",
    COMPANY: "Domiziani Design",
    LINK: "https://youtube.com/embed/Qdg5yQ5puqM",
  },
  {
    id: 34,
    CATEGORY: "Process",
    TITLE: "Domiziani Design",
    COMPANY: "Domiziani Design",
    LINK: "https://youtube.com/embed/ugCkdKgRGp0",
  },
  {
    id: 35,
    CATEGORY: "Products",
    TITLE: "DOMIZIANI SUMMER SALE",
    COMPANY: "Domiziani Design",
    LINK: "https://youtube.com/embed/NhAJ7waCapE",
  },
];
